language: go
go:
  - 1.9
node_js: '7'
services:
  # - mysql
before_install:
- nvm install 6.9
- nvm use 6.9
install:
- npm install -g yarn
- go get -t ./...
before_script:
- cd frontend/
- yarn install
# - cp src/config.example.js src/config.js
- cd ..
script:
- ./test_cov.sh
- cd frontend/
- npm test -- --coverage
- npm run build
- cd ..
after_success:
- bash <(curl -s https://codecov.io/bash)
- cd frontend/
- bash <(curl -s https://codecov.io/bash)
- cd ..
