go:
  - "1.9"
  - "1.10.x"
  - master
node_js: "7"
before_install:
  - nvm install 6.9
  - nvm use 6.9
install:
  - npm install -g yarn
  - go get -t ./...
before_script:
  - cd ui/
  - yarn install
  # - cp src/config.example.js src/config.js
  - cd ..
script:
  - ./test_cov.sh
  - cd ui/
  - npm test -- --coverage
  - npm run build
  - cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd ui/
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
