go:
  - "1.9"
  - "1.10.x"
  - master
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - nvm install 6.9
  - nvm use 6.9
  - go get -u github.com/golang/dep/...
install:
  - npm install -g yarn
  - dep ensure
before_script:
  - cd ui/
  - yarn install
  - cd ..
script:
  - ./test_cov.sh
  - cd ui/
  - npm test -- --coverage
  - npm run build
  - cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd ui/
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
