# system config and tuning
inputs:
  rpc:
    address: ":8888"
  http:
    address: ":8080"
    ws-tick: 200ms
  # homekit:
  #   pin: "10000000"
outputs:
  # ola:
  #   address: "localhost:9010"
  #   tick: 40ms
  hue:
    address: "10.0.0.39"
    username: "foo"
# tracing:
#   server: "localhost:6831"
#   servicename: "hyperion-server"
timings:
  fade-interpolation-tick: 30ms
  cue-backoff: 50ms

# more user specific config - things that will change more frequently
triggers:
  - command: set(hue2:blue:1000)
    source: "homekit-switch"
    id: 4
  - command: set(hue1:red:1000)
    source: "homekit-switch"
    id: 4

lights:
  hue:
    - hue_id: 1
      name: hue1
    - hue_id: 4
      name: hue2
    - hue_id: 9
      name: c1
    - hue_id: 10
      name: c2
    - hue_id: 8
      name: c3
    - hue_id: 13
      name: c4
    - hue_id: 12
      name: c5
    - hue_id: 11
      name: c6
  dmx:
    - name: par1
      start_address: 1
      universe: 1
      profile: rgbw-par-a
    - name: par2
      start_address: 18
      universe: 1
      profile: rgbw-par-a
    - name: light1
      start_address: 8
      universe: 1
      profile: rgbw-par-a
  generic:
    - name: generic1
dmx_profiles:
  - rgbw-par-a:
      notes: A001 means 4 channel mode, starting on address 1
      capabilities:
        - rgbw
      channels:
        red: 1
        green: 2
        blue: 3
        white: 4

jobs:
  - command: set(hue2:#FF00FF:0)
    cron: 1-59/2 * * * *
    name: test1
  - command: set(hue2:#0000FF:0)
    cron: "*/2 * * * *"

commands:
  - setall:
      body: |
        function process()
          actions = {}
          for i, light in ipairs(light_list) do
            table.insert(actions, {
              light = light,
              color = rgb_to_hex(100,0,120),
              timing = "1s"
            })
          end
          frame1 = {
            actions = actions
          }
          return {
            frames = {frame1}
          }
        end
