version: "3"
services:
  jaeger:
    container_name: jaeger-hyperion
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # http
      - "14268:14268"
      - "9411:9411"
    image: "jaegertracing/all-in-one:1.10"
